### ISSUE TITLE
Power / Led

### ISSUE THREAD

**Issue by Nastras** [klanchman/homebridge-logi-circle-controls#1]
Hello, thanks for this little but really useful plugin. Is it possible that you add other features that are not available in HomeKit like power or LED on / off?

Greeting Nastra

**Comment by klanchman** [comment]
Sorry for the late reply to this, for some reason I did not receive any email about this issue.

I like the idea, and I should be able to add these switches pretty easily!

Power on/off ties in with the "privacy" idea well, but the LED not as much. In doing this I think I will rename the plugin, and think about adding even more options in the future.

**Comment by Nastras** [comment]
Hello, great that you have answered. The idea to rename the plugin and then add new features I find really great. I'm curious.

I also like to test it .-)

**Comment by klanchman** [comment]
I just moved the repo/package to `homebridge-logi-circle-controls` and published version 1.0.0, which adds the ability to control the camera's on/off switch and the LED on/off switch.

Please refer to the readme for instructions on how to set this up. Please note that the configuration has changed in multiple ways. Most importantly, it's now a platform instead of just an accessory!

Please let me know if you run into any issues 😄

**Comment by Nastras** [comment]
Sorry for the late reply. I was on vacation .-)

Thanks again for the quick implementation of additional features. Unfortunately, I have a problem if I want to integrate two cameras in the config.

I get this error when starting the Homebridge instance:

![ohne titel](https://user-images.githubusercontent.com/27686185/44615611-835aba00-a83e-11e8-9941-e7eb6b00413e.jpeg)

My config is valid and looks like this:

{
"bridge": {
"name": "Homebridge-logi-circle-controls",
"username" : "",
"port" : ,
"pin": "",
"manufacturer": "",
"model": ""
},

"plugins": [
"homebridge-logi-circle-controls"
],

"accessories": [
],

"platforms": [
{
"platform": "Logi Circle Controls",
"name": "Kamera Steuerung Balkon",
"deviceId": "",
"email": "",
"password": "",
"accessories":
[
{
    "type": "privacyMode",
    "name": "Privatmodus"
},
{
    "type": "streamingMode",
    "name": "Streammodus"
}, 
{
    "type": "ledPower",
    "name": "Led"
}
]
},
{	
"name": "Kamera Steuerung Garage",
"deviceId": "",
"email": "",
"password": "",
"accessories":
[
{
    "type": "privacyMode",
    "name": "Privatmodus"
},
{
    "type": "streamingMode",
    "name": "Streammodus"
}, 
{
    "type": "ledPower",
    "name": "Led"
}
]
}
]
}


Do you have an idea where the problem is?

Greeting nastra

**Comment by klanchman** [comment]
Hope you enjoyed your vacation! 😄 

It looks like the second entry in your `platforms` does not have a `platform` field, which I think Homebridge needs to have there.

Having said that, it looks like Homebridge does not support having more than 1 instance of a single platform (see here: https://github.com/nfarina/homebridge/issues/1736).

This plugin should be able to support controlling multiple devices though! I opened issue #3 for adding that feature. (I only have 1 camera though, so I won't be able to test it very well.)

**Comment by Nastras** [comment]
I also tried the field Platform in my config during the test. I got the same mistake as in the issue because you have linked. So I tried it without a platform in the config. Thought that it was the right way.

If you have installed the more multipple devices support I like to test it with both cameras.

Thank you!
