### ISSUE TITLE
Camera switch not toggling back on

### ISSUE THREAD

**Issue by ahrenstein** [klanchman/homebridge-logi-circle-controls#13]
Problem: If the Circle app is used to turn off the camera stream, the camera switch in Home.app correctly turns off. However, if the Circle app is used to turn the camera stream on, the camera switch in Home.app stays off. Toggling it on manually, does nothing as the camera is already on. Toggling it on and off in Home.app directly works though. This could give a Home.app only user the wrong status of the camera if they don't also have access to the Circle app, or if they don't check the Circle app, but used it last to toggle the camera.

iOS Device: iPhone 7 running 12.2 on same WiFi network.
WiFi AP: Meraki MR33
Homebridge Version: 0.4.47
Plugin Version: 2.1.0
Relevant config section:
```
 {
            "platform": "Logi Circle Controls",
            "name": "<Optional: the desired name for the platform (mostly affects Homebridge logs) | Default: 'Logi Circle Controls'>",
            "email": “[REDACTED]”,
            "password": "[REDACTED]",
            "accessories": [
                {
                    "deviceId": "[REDACTED]",
                    "name": "Dining Room",
                    "camera": {
                        "name": "DR Camera",
                        "disabled": false
                    },
                    "led": {
                        "name": "DR Camera LED",
                        "disabled": false
                    },
                    "privacyMode": {
                        "name": "DR Camera Privacy Mode",
                        "disabled": true
                    },
                    "recording": {
                        "name": "DRT Camera Recording",
                        "disabled": false
                    }
                }
            ]
        }
```

**Comment by ahrenstein** [comment]
I'm happy to provide sanitized logs if that helps debug this. Using HomePod and AppleTV 4 as hubs. All devices on latest iOS/tvOS/firmware.

Thanks for the great plugin!

**Comment by klanchman** [comment]
Thanks for the feedback! I'm seeing the same issue, and seems a bit different than #12 because even killing the Home app doesn't change the Camera switch, but _does_ update the others. I will take a closer look at this soon, hopefully this weekend 😄

**Comment by klanchman** [comment]
Hey @ahrenstein, please check out version 2.1.1 that I just published, it should fix the issue!
Logitech changed a property slightly on their API.

**Comment by ahrenstein** [comment]
Awesome! I'll test it out tonight and report back.

**Comment by ahrenstein** [comment]
I can confirm this is fixed now. Thanks!
