### ISSUE TITLE
Camera ID

### ISSUE THREAD

**Issue by Hussamfhaily** [klanchman/homebridge-logi-circle-controls#20]
Hi. How can I get the camera ID. It is updated with HomeKit firmware so I can’t find it in my account. Regards.

**Comment by klanchman** [comment]
Hello! Unfortunately this plugin doesn't support HomeKit Secure Video, see issue #19.
If the plugin offers features that HomeKit Secure Video doesn't have, I'd recommend you either revert your firmware back to Logitech's so you can use the plugin, or send feedback to Apple about what features you'd like them to add.
