### ISSUE TITLE
Camera still showing live feed in Home App.

### ISSUE THREAD

**Issue by QandnotU** [klanchman/homebridge-logi-circle-controls#8]
@klanchman Thank you for creating this plugin. Question...I have Streaming and Privacy switches off, but I'm still able to see the thumbnails every 10 seconds as well as able to stream the feed live within the Home App. The Logi Cicle app seems to be respond accordantly, but Home app seems unaffected.

**Comment by klanchman** [comment]
Interesting! I see the same thing on mine.

You'll also notice that when you use the Logitech app to view a stream, the camera's LED turns green to indicate that someone is watching the stream. However, the LED does _not_ change color when you access it via the Home app.

My best guess is that the streaming mode setting doesn't affect anything at a hardware level on the camera. Logitech probably uses it in their app to disallow viewing the stream, whereas HomeKit is probably blissfully unaware of it.

The video stream in the Home app is not provided by this plugin, so I think it'd be up to Logitech to change how the streaming mode toggle behaves with HomeKit.

**Comment by QandnotU** [comment]
@klanchman is it possible to expose a switch that taps into this?

https://developer.apple.com/documentation/homekit/hmcamerastreamcontrol
