### ISSUE TITLE
Reverse privacy mode switch

### ISSUE THREAD

**Issue by nilsivanilli** [klanchman/homebridge-logi-circle-controls#9]
Hi @klanchman, is it possible to reverse the "privacyMode" switch? At the moment the state of the "privacyMode" switch is always opposite to what the Logi Circle app shows and this confuses me a lot, i.e. "privacyMode" switch OFF means that the "recording" switch in the Logi app is ON and vice versa. Of course "privacyMode" OFF means "forget about privacy, you are allowed to record" that is why the "recording" switch in the Logi app is ON but in my opinion it would be better to have a switch state which matches the setting in the Logi Circle app.

The state of the "streamingMode" switch already matches the setting (Camera on/off) found in the Logi Circle app and also the "ledPower" switch works identical to its counter part (LED on/off) in the Logi Circle app. That is why I would love to have the "privacyMode" reversed so that it resembles a "recordingMode" switch instead and now can work exactly as its counter part (Recording on/off) in the Logi Circle app.

After being reversed I would subsequently rename the "privacyMode" switch to "recordingMode" and maybe also make things clearer for the "streamingMode" i.e. renaming the latter to "cameraState" or something similar.

streamingMode -> cameraState = Logi Circle App: Camera
privacyMode **reversed** -> recordingMode = Logi Circle App: Recording
ledPower = Logi Circle App: LED

**Comment by klanchman** [comment]
Thanks for your feedback!

The switch actually used to be called "Privacy Mode" in the Logitech app (and is still called `privacyMode` on their API), hence the name here. 

I like the idea of calling the switches `camera`, `recording`, and `led`. I will work on making that change sometime soon. I may not immediately rename everything to cut down on breaking changes, I might introduce new switch names instead and deprecate the existing ones. I'll see what makes sense.

In the meantime, I have updated the documentation to be clearer about what all the switches do. 😄

**Comment by nilsivanilli** [comment]
I did not know that it used to be called that way, many thanks for clarifying Kyle! It would be nice to see renamed switches on a future version, but no hurry! :)

I just had a look at your updated documentation; I think the paragraph referring to #8 needs to be moved up from "streamingMode" to "privacyMode": 
 - The `privacyMode` switch only disables/enables (automatic) recording to the internet. If privacyMode is ON, i.e. (automatic) recording in the Logi Circle App is OFF, you are still able to manually jump into the camera via the Home or Logi Circle app and get a live feed. So this switch just stops recording / saving videos to the internet cloud storage afaik.
- Whereas the `streamingMode` switch completely turns the camera's video signal on or off. If turned OFF even a live feed is no longer possible, neither with the Home app nor with the Logi Circle app.


My only wish would be to have an option to reverse the `privacyMode` switch so that it has the same state like the button in the Logi Circle app. Is there an option available so that I can reverse it in the config like shown in my screenshot?
<img width="758" alt="2019-01-05_212124" src="https://user-images.githubusercontent.com/46399241/50729064-a3c34b00-1133-11e9-9fd1-a1ab9a9811ff.png">

Many thanks for all your help and for developing this awesome plugin! :)

Cheers, Nils

**Comment by klanchman** [comment]
Hi Nils,

> I think the paragraph referring to #8 needs to be moved...

Issue #8 does actually refer `streamingMode`. You'll notice that if `streamingMode` is off, you _can_ still view the camera in the Home app. I don't think there's anything this plugin can do to fix that, so I found it worth pointing out.

> option to reverse the privacyMode switch

I'll consider adding an option to invert switches. I think having too many options available will make the configuration more difficult to explain/understand, though. Something I'll think about.

**Comment by nilsivanilli** [comment]
Hi Kyle,

> You'll notice that if streamingMode is off, you can still view the camera in the Home app.

hm strange, I just double checked and cannot confirm the behavior you mention. On my device if `streamingMode` is _off_ (i.e. the camera is _off_) I am not able to view the camera at all, so there is no live feed with either apps. Also the Home app says in German "Keine Antwort - Diese Kamera antwortet nicht" (~does not respond) and the Logi Circle app says "Ausgeschaltet" or "Video der Circle-Kamera ist ausgeschaltet" (~switched off). There is no video signal available in both apps, only the last still picture captured before the camera got switched off is shown. 

After switching streamingMode on again I checked the `privacyMode` behavior:
- If privacyMode is _activated_ on my device (i.e. automatic recording with saving to the internet is _off_) I am able to view the camera, so I will at least get a live feed in both apps. The Logi Circle app also shows a camera icon with a crossed out x to indicate that automatic recording with saving to the internet is off.
- If privacyMode is _deactivated_ (i.e. automatic recording with saving to the internet is _on_) this camera icon with a crossed out x disappears because the camera now also records and saves to the internet automatically if motion is detected.

So on my device the privacyMode switch cannot disable the live feed, it is always available. Only the streamingMode switch mentioned at the very top can disable the live feed at least on my device. But all in all it does not matter.

> I'll consider adding an option to invert switches. I think having too many options available will make the configuration more difficult to explain/understand, though. Something I'll think about.

I would really appreciate to being able to invert the switch but also understand that other things are probably more important.

Again many thanks for all your support! :)

Regards
Nils

**Comment by klanchman** [comment]
Oh interesting! I just checked streamingMode on mine and it seems to be working like I’d expect now. I guess Logitech must have fixed that problem sometime recently. :smile:

**Comment by klanchman** [comment]
I published a new beta of the package that has new switch names, including a new `recording` switch.

You can install the beta like this:

```
npm i -g homebridge-logi-circle-controls@next
```

You can find the README for the beta version [here](https://github.com/klanchman/homebridge-logi-circle-controls/blob/feature/9-rename-switches/README.md).

Please note that the recording switch is disabled by default, you need to explicitly enable it in your config.

Let me know if you run into any issues with the beta!

**Comment by nilsivanilli** [comment]
It works like a charm, thank you so much! 🙂 I enabled the record switch and disabled the old privacyMode switch and now everything behaves exactly like the buttons inside the Logi Circle app.

One general thing I noticed: if I press the streamingMode / privacyMode / ledPower or remote switch in the Home app, the corresponding Logi Circle app buttons will recognize it almost immediately as well. But if I click a button inside the Logi Circle app, the corresponding streamingMode / privacyMode / ledPower / recording switch in the Home app does not realize it had been changed so I usually have to close and reopen the Home app for the switches to refresh. Just a minor thing though, since I do not want to use the Logi Circle app. 🙂

**Comment by klanchman** [comment]
Thanks for testing! This is now available in [2.1.0](
https://github.com/klanchman/homebridge-logi-circle-controls/releases/tag/2.1.0).

As far as the switches updating slowly, it seems like the Home app doesn't ask the plugin to refresh the statuses very often. Logitech's app seems to ask for new statuses more often. I created issue #12 to research if there's a way to handle this 😄
